name: Generate terraform docs
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.11.0
      with:
        working-dir: ./terraform,./terraform/example
        output-file: README.md
        output-method: inject
        git-push: "true"